#pragma once
#include <string>
#include <functional>
#include <stdexcept>
#include <memory>
#include <cstdint>
#include "r66_strings.hpp"

namespace R66::PAL {
	class MissingPalImpl : public std::runtime_error {
	public:
		MissingPalImpl(const char* msg) : std::runtime_error(msg) { }
	};

	typedef void (*ProxyPALImpl)(void* parent, int32_t call, void* payload);
}
#include "pal_autogenerated.hpp"
